codecov:
  notify:
    wait_for_ci: false

coverage:
  precision: 1
  # PRs can result in small changes of e.g. 0.04 percent; don't let these
  # prevent a passing check
  status:
    project:
      default:
        threshold: 0.2%

comment:
  layout: "diff, files"

ignore:
# Prevent false check failures on GitHub
- message_ix/testing/nightly.py
