version: 2 
updates: 
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule: 
      interval: "weekly" 
    # Add assignees 
    assignees: 
      - "glatterf42" 
      - "khaeru" 
    # Specify labels 
    labels: 
      - "dependencies" 
    # Add reviewers:
    reviewers: 
      - "glatterf42" 
      - "khaeru" 