version: 2 
updates: 
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule: 
      interval: "monthly" 
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      all-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*" # All dependencies in the package-ecosystem
    # Add assignees 
    assignees: 
      - "glatterf42" 
      - "khaeru" 
    # Specify labels 
    labels: 
      - "dependencies" 
    # Add reviewers:
    reviewers: 
      - "glatterf42" 
      - "khaeru"
  - package-ecosystem: "github-actions"
    # Only update major versions
    ignore:
      - dependency-name: "*"
        update-types:
        - "version-update:semver-minor"
        - "version-update:semver-patch"
    # Below config mirrors the example at
    # https://github.com/dependabot/dependabot-core/blob/main/.github/dependabot.yml
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      all-actions:
        patterns: [ "*" ]
     # Add assignees 
    assignees: 
      - "glatterf42" 
      - "khaeru" 
    # Specify labels 
    labels: 
      - "dependencies" 
    # Add reviewers:
    reviewers: 
      - "glatterf42" 
      - "khaeru" 
  
    