import subprocess
import sys

import matplotlib.pyplot as plt

from contextlib import contextmanager

import ixmp

firstyear = 2010


def check_local_model(model, notebook, shell=False):
    mp = ixmp.Platform(dbtype='HSQLDB')
    if model in mp.scenario_list().model.unique():
        mp.close_db()
        return

    mp.close_db()
    pyversion = sys.version_info[0]
    cmd = "jupyter nbconvert {} --ExecutePreprocessor.kernel_name='python{}' --execute"
    cmd = cmd.format(notebook, pyversion)
    subprocess.check_call(cmd.split(), shell=shell)


class Plots(object):

    def __init__(self, ds, country):
        self.ds = ds
        self.country = country

    def plot_demand(self, light_demand, elec_demand):
        fig, ax = plt.subplots()
        l = light_demand['value']
        l.plot(ax=ax, label='light')
        e = elec_demand['value']
        e.plot(ax=ax, label='elec')
        (l + e).plot(ax=ax, label='total')
        plt.ylabel('GWa')
        plt.xlabel('Year')
        plt.legend(loc='best')

    def plot_vintages(self, var, baseyear=False, subset=None):
        df = self.ds.var(var)
        if not baseyear:
            df = df[df['year_vtg'] > firstyear]
        if subset is not None:
            df = df[df['technology'].isin(subset)]
        idx = ['year_act', 'technology']
        df = df[idx + ['year_vtg', 'lvl']].groupby(idx).sum().reset_index()
        df.pivot(index='year_act', columns='technology',
                 values='lvl').plot.bar(stacked=True)

    def plot_activity(self, baseyear=False, subset=None):
        self.plot_vintages('ACT', baseyear=baseyear, subset=subset)
        plt.title('{} Energy System Activity'.format(self.country.title()))
        plt.ylabel('GWa')
        plt.xlabel('Year')
        plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))

    def plot_capacity(self, baseyear=False, subset=None):
        self.plot_vintages('CAP', baseyear=baseyear, subset=subset)
        plt.title('{} Energy System Capacity'.format(self.country.title()))
        plt.ylabel('GWa')
        plt.xlabel('Year')
        plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))

    def plot_no_vintage(self, var, baseyear=False, subset=None):
        df = self.ds.var(var)
        if not baseyear:
            df = df[df['year_vtg'] > firstyear]
        if subset is not None:
            df = df[df['technology'].isin(subset)]
        df.pivot(index='year_vtg', columns='technology',
                 values='lvl').plot.bar(stacked=True)

    def plot_new_capacity(self, baseyear=False, subset=None):
        self.plot_no_vintage('CAP_NEW', baseyear=baseyear, subset=subset)
        plt.title('{} Energy System New Capcity'.format(self.country.title()))
        plt.ylabel('GWa')
        plt.xlabel('Year')
        plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))

    def plot_equ(self, equ, value, baseyear=False, subset=None):
        df = self.ds.equ(equ)
        if not baseyear:
            df = df[df['year'] > firstyear]
        if subset is not None:
            df = df[df['commodity'].isin(subset)]
        df = df.pivot(index='year', columns='commodity', values=value)
        df.plot.bar(stacked=False)

    def plot_prices(self, baseyear=False, subset=None):
        self.plot_equ('COMMODITY_BALANCE', 'mrg',
                      baseyear=baseyear, subset=subset)
        plt.title('{} Energy System Prices'.format(self.country.title()))
        plt.ylabel('$/GWa')
        plt.xlabel('Year')
        plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))


@contextmanager
def read_scenario(platform, name, scen):
    mp = platform
    close = mp.dbtype == 'HSQLDB'
    if close:
        mp.open_db()
    ds = mp.Scenario(name, scen)
    yield ds
    if close:
        try:
            mp.close_db()
        except:
            return


@contextmanager
def make_scenario(platform, country, name, base_scen, scen):
    mp = platform
    close = mp.dbtype == 'HSQLDB'
    if close:
        mp.open_db()
    base_ds = mp.Scenario(name, base_scen)
    ds = base_ds.clone(
        name, scen, "scenario generated by 'tutorial/tools.py:scenario_ds()', {} - {}".format(name, scen), keep_sol=False)
    ds.check_out()
    yield ds
    ds.commit(
        "changes committed by 'tutorial/tools.py:scenario_ds()' {} - {}".format(name, scen))
    ds.set_as_default()
    ds.solve('MESSAGE')
    if close:
        try:
            mp.close_db()
        except:
            return
