# Verify that installation from conda-forge works as intended
name: Install from conda-forge

on:
  # 05:00 UTC = 06:00 CET = 07:00 CEST
  schedule:
  - cron: "0 5 * * *"
  # Uncomment to debug
  # pull_request:
  #   branches: [ main ]

env:
  # Oldest version that can reliably be downloaded
  GAMS_VERSION: 48.7.0

jobs:
  conda:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    # As suggested by conda-incubator/setup-miniconda
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Setup Anaconda or miniconda
      uses: conda-incubator/setup-miniconda@v4
      with:
        activate-environment: testenv
        channel-priority: strict
        channels: conda-forge
        python-version: "3.14"

    - name: Cache GAMS installer
      uses: actions/cache@v6
      with:
        path: |
          gams
        key: ${{ matrix.os }}-gams${{ env.GAMS_VERSION }}
        restore-keys: |
          ${{ matrix.os }}-

    - uses: iiasa/actions/setup-gams@main
      with:
        version: ${{ env.GAMS_VERSION }}
        license: ${{ secrets.GAMS_LICENSE }}

    - name: Install message-ix into 'testenv' conda environment
      # Also install pytest and packages required for testing. pip and related
      # tools support this via message_ix[testing], but conda does not.
      run: |
        conda install message-ix pytest asyncssh sphinx
        conda list
        conda info

    - name: Check message-ix and ixmp CLIs
      run: |
        message-ix show-versions
        ixmp --platform default list || true

    - name: Run a test from the test suite to touch JDBCBackend/Java via JPype
      run: pytest --pyargs message_ix -p ixmp.testing -p message_ix.testing -p no:faulthandler -k "test_add_cat" --verbose -rA --color=yes
