name: nightly
# This workflow is a stripped-down version of pytest.yaml, with multi-OS
# features removed.

on:
  # Uncomment these two lines for debugging, but leave them commented on the
  # master branch
  # pull_request:
  #   branches: [ master ]
  schedule:
  # 05:00 UTC = 06:00 CET = 07:00 CEST
  - cron: "0 5 * * *"

env:
  GAMS_VERSION: 25.1.1
  # See description in lint.yml
  depth: 100

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
    - name: Check out ixmp
      uses: actions/checkout@v2
      with:
        repository: iiasa/ixmp
        path: ixmp
        fetch-depth: ${{ env.depth }}

    - name: Check out message_ix
      uses: actions/checkout@v2
      with:
        path: message_ix
        fetch-depth: ${{ env.depth }}

    - name: Fetch tags (for setuptools-scm)
      run: |
        (cd ixmp; git fetch --tags --depth=${{ env.depth }})
        (cd message_ix; git fetch --tags --depth=${{ env.depth }})

    - uses: actions/setup-python@v2
      with:
        # This should match the "Latest version testable on GitHub Actions"
        # in pytest.yml
        python-version: "3.8"

    - name: Cache GAMS installer and Python packages
      uses: actions/cache@v2
      with:
        path: |
          gams
          ~/.cache/pip
          ~/Library/Caches/pip
          ~/appdata/local/pip/cache
        key: gams${{ env.GAMS_VERSION }}

    - name: Install GAMS
      env:
        CI_OS: ubuntu
      run: ixmp/ci/install-gams.sh

    - name: Install Python packages and dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools-scm
        (cd ixmp; pip install .[tests])
        (cd message_ix; pip install .[tests])

    - name: Run test suite using pytest
      env:
        MESSAGE_IX_CI_USER: ${{ secrets.ENE_DATA_USER }}
        MESSAGE_IX_CI_PW: ${{ secrets.ENE_DATA_PASS }}
      working-directory: message_ix
      run: pytest message_ix -m nightly --verbose
