name: Receive pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get user permission
        uses: actions-cool/check-user-permission@v2
        id: checkAccess
        with:
          require: write
          username: ${{ github.triggering_actor }}
      - name: Ensure user permission
        if: steps.checkAccess.outputs.require-result == 'false'
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}"
          exit 1
